export const LIFE_CONFIG: ILifeConfig = {
  INITIAL_RADIUS: 5,
  MAX_RADIUS: 15,
  MIN_RADIUS: 2,
  SPEED: 1.2,
  MATING_DISTANCE: 15,
  GESTATION_PERIOD: 300,
  HUNGER_LIMIT: 1000,
  HUNGER_THRESHOLD_FOR_MATING: 500,
  FULLNESS_DURATION: 100,
  SIZE_INCREMENT: 0.5,
  SIZE_DECREMENT: 0.005,
  AGE_LIMIT: 1500,
  REST_CHANCE: 0.002,
  REST_MIN_DURATION: 20,
  REST_MAX_DURATION: 60,
};

export interface ILifeConfig {
  INITIAL_RADIUS: number;
  MAX_RADIUS: number;
  MIN_RADIUS: number;
  SPEED: number;
  MATING_DISTANCE: number;
  GESTATION_PERIOD: number;
  HUNGER_LIMIT: number;
  HUNGER_THRESHOLD_FOR_MATING: number;
  FULLNESS_DURATION: number;
  SIZE_INCREMENT: number;
  SIZE_DECREMENT: number;
  AGE_LIMIT: number;
  REST_CHANCE: number;
  REST_MIN_DURATION: number;
  REST_MAX_DURATION: number;
}
